title: Trace Winkler | Data Science Portfolio
logo: /images/IMG_3859.jpeg
description: This portfolio was created in order to document my progress as I continue to learn
theme: jekyll-theme-minimal
show_downloads: false
